import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react-swc'
import tailwindcss from '@tailwindcss/vite'
import { minify } from 'terser'
import { readFileSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

/**
 * Vite plugin that compiles src/utils/dfmBookmarklet.js
 * into src/utils/bookmarkletCode.js on every `dev` start and `build`.
 */
function bookmarkletPlugin() {
  return {
    name: 'build-bookmarklet',
    async buildStart() {
      const srcPath = resolve(__dirname, 'src/utils/dfmBookmarklet.js')
      const outPath = resolve(__dirname, 'src/utils/bookmarkletCode.js')
      const src = readFileSync(srcPath, 'utf-8')

      const result = await minify(src, {
        compress: { drop_console: false, passes: 2 },
        mangle: true,
        format: { comments: false },
      })

      if (result.error) {
        this.error(`Bookmarklet minification failed: ${result.error}`)
        return
      }

      const moduleContent = `// ⚠️ Auto-generated by vite bookmarkletPlugin — Do not edit manually!
// Source: src/utils/dfmBookmarklet.js
export const bookmarkletCode = ${JSON.stringify(result.code)};
`
      writeFileSync(outPath, moduleContent, 'utf-8')
      console.log(`📟 Bookmarklet compiled (${result.code.length} chars)`)
    },
  }
}

// https://vite.dev/config/
export default defineConfig({
  base: '/DfM-Ninja/',
  plugins: [
    bookmarkletPlugin(),
    react(),
    tailwindcss(),
  ],
  server: {
    port: Number(process.env.PORT) || 5178,
  },
})
