import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react-swc'
import tailwindcss from '@tailwindcss/vite'
import { viteSingleFile } from 'vite-plugin-singlefile'
import { minify } from 'terser'
import { readFileSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

/**
 * Vite plugin that compiles src/utils/dfmBookmarklet.js
 * into src/utils/bookmarkletCode.js on every `dev` start and `build`.
 */
function bookmarkletPlugin() {
  return {
    name: 'build-bookmarklet',
    async buildStart() {
      const compile = async (srcFile, outFile, varName) => {
        const srcPath = resolve(__dirname, srcFile)
        const outPath = resolve(__dirname, outFile)
        let src;
        try {
          src = readFileSync(srcPath, 'utf-8')
        } catch (e) {
          return;
        }

        const result = await minify(src, {
          compress: { drop_console: false, passes: 2 },
          mangle: true,
          format: { comments: false },
        })

        if (result.error) {
          this.error(`Bookmarklet minification failed: ${result.error}`)
          return
        }

        const moduleContent = `// ⚠️ Auto-generated by vite bookmarkletPlugin — Do not edit manually!
// Source: ${srcFile}
export const ${varName} = ${JSON.stringify(result.code)};
`
        writeFileSync(outPath, moduleContent, 'utf-8')
        console.log(`📟 Bookmarklet compiled (${result.code.length} chars): ${srcFile}`)
      }

      await compile('src/utils/dfmBookmarklet.js', 'src/utils/bookmarkletCode.js', 'bookmarkletCode')
      await compile('src/utils/dfmBookmarkletLocal.js', 'src/utils/bookmarkletLocalCode.js', 'bookmarkletLocalCode')
    },
  }
}

// https://vite.dev/config/
export default defineConfig({
  base: process.env.VITE_LOCAL_BUILD === '1' ? './' : '/DfM-Ninja/',
  plugins: [
    bookmarkletPlugin(),
    react(),
    tailwindcss(),
    ...(process.env.VITE_LOCAL_BUILD === '1' ? [viteSingleFile()] : [])
  ],
  server: {
    port: Number(process.env.PORT) || 5178,
  },
})
